# Generated by Django 5.1 on 2024-08-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='student',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='title',
        ),
    ]
